# This file is provided so that the application can be compiled using Twister,
# the Zephyr testing tool. In this file, multiple combinations can be specified,
# so that you can easily test all of them locally or in CI.
app:
  description: libzdriver
  name: libzdriver
common:
  build_only: true
  integration_platforms:
    - tbot
tests:
  app.default: {}
  app.debug:
    extra_overlay_confs:
      - debug.conf
